
<?php
	// require 'vendor/autoload.php';
	// $email = new \SendGrid\Mail\Mail();
	// if(isset($_POST)) {
	// 	$visitor_name = "";
  //   $visitor_email = "";
  //   $email_title = "";
  //   $visitor_message = "";
  //   if(isset($_POST['visitor_name']) && isset($_POST['visitor_email'])) {
  //   	$visitor_email = str_replace(array("\r", "\n", "%0a", "%0d"), '', $_POST['visitor_email']);
  //     $visitor_email = $visitor_email;
  //     $visitor_name = $_POST['visitor_name'];
	// 		$email->setFrom($visitor_email, $visitor_name);
	//
	//   }
  //   if(isset($_POST['email_title'])) {
	//     $email_title = $_POST['email_title'];
	// 		$email->setSubject($email_title);
  //   }
  //   if(isset($_POST['visitor_message'])) {
  //     $visitor_message = htmlspecialchars($_POST['visitor_message']);
	// 		$email->addContent("text/plain", $visitor_message);
  //   }
	// 	// $recipient = "atomifak@gmail.com";
  //   $recipient = "info@uniqueoceans.com";
  //   $sendgrid = new \SendGrid('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');
  //   try {
  //   	$email->addTo($recipient, "Unique Oceans Contact");
	//     $response = $sendgrid->send($email);
	//
	//     // print $response->statusCode() . "\n";
	//     // print_r($response->headers());
	//     // print $response->body() . "\n";
	//     $message = 'success';
	// 	} catch (Exception $e) {
	// 	    // echo 'Caught exception: '. $e->getMessage() ."\n";
	// 	    $message =  'error';
	// 	}
	//
  //   $review_url = '' . $_SERVER['HTTP_REFERER'] . '?status=' . $message;
	// 	header('Location: ' . $review_url);
	// } else {
	//     echo '<p>Something went wrong</p>';
	// }
	// echo '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'; exit;


	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/



	// $ch = curl_init();
	//
	// curl_setopt($ch, CURLOPT_URL, 'https://api.sendgrid.com/v3/mail/send');
	// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	// curl_setopt($ch, CURLOPT_POSTFIELDS, "{"personalizations": [{"to": [{"email": "atomifak@gmail.com"}]}],"from": {"email": "atfaktech@gmail.com"},"subject": "Hello, World!","content": [{"type": "text/plain", "value": "Heya!"}]}");
	// curl_setopt($ch, CURLOPT_POST, 1);
	//
	// $headers = array();
	// $headers[] = 'Authorization: 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';
	// $headers[] = 'Content-Type: application/json';
	// curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);





	//
	// $result = curl_exec($ch);
	// if (curl_errno($ch)) {
	//     echo 'Error:' . curl_error($ch);
	// }
	// curl_close ($ch);

	require 'vendor/autoload.php';
	$email = new \SendGrid\Mail\Mail();
	if(isset($_POST['visitor_name']) && isset($_POST['visitor_email'])) {
		$email->setFrom($_POST['visitor_email'], $_POST['visitor_name']);
		$email->setSubject($_POST['email_title']);
		// $recipient = "atomifak@gmail.com";
	  $recipient = "info@uniqueoceans.com";
		$email->addTo($recipient, "Unique Ocean contact");
		$email->addContent("text/plain", htmlspecialchars($_POST['visitor_message']));
		$email->addContent(
		    "text/html",  htmlspecialchars($_POST['visitor_message'])
		);
		$sendgrid = new \SendGrid('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');
		try {
		    $response = $sendgrid->send($email);
		    // print $response->statusCode() . "\n";
		    // print_r($response->headers());
		    // print $response->body() . "\n";
				$message = 'success';
		} catch (Exception $e) {
		    // echo 'Caught exception: '. $e->getMessage() ."\n";
				$message =  'error';
		}

		$review_url = '' . $_SERVER['HTTP_REFERER'] . '?status=' . $message;
	 	header('Location: ' . $review_url);
	} else {
		$message = 'incomplete';
	 	$review_url = '' . $_SERVER['HTTP_REFERER'] . '?status=' . $message;
 		header('Location: ' . $review_url);
	}
?>
